language: objective-c
osx_image: xcode7.2
script:
  - xcodebuild test -scheme OptionalExtensions-Mac
  - xcodebuild test -scheme OptionalExtensions-iOS -sdk iphonesimulator
  - xcodebuild test -scheme OptionalExtensions-tvOS -sdk appletvsimulator
  - xcodebuild build -scheme OptionalExtensions-watchOS -sdk watchsimulator